name: ParentPearl CI/CD

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:15
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: chaabat
                    POSTGRES_DB: parentpearl
                ports:
                    - "5432:5432"
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: "17"
                  distribution: "temurin"
                  cache: maven

            - name: Build with Maven
              run: mvn -B package --file backend/pom.xml -DskipTests

            - name: Run tests
              run: mvn test --file backend/pom.xml
              env:
                  SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/parentpearl
                  SPRING_DATASOURCE_USERNAME: postgres
                  SPRING_DATASOURCE_PASSWORD: chaabat
